-- 코드를 작성해주세요
SELECT 
    L.ID,
    IFNULL(R.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA L
LEFT JOIN (
    SELECT I.PARENT_ID, COUNT(I.ID) AS CHILD_COUNT FROM ECOLI_DATA I
    GROUP BY I.PARENT_ID HAVING I.PARENT_ID IS NOT NULL
) R ON L.ID = R.PARENT_ID
