-- 코드를 입력하세요
SELECT
    L.FOOD_TYPE,
    L.REST_ID,
    L.REST_NAME,
    R.MAX_FAVORITES AS FAVORITES
FROM REST_INFO L 
JOIN (
    SELECT
        M.FOOD_TYPE,
        MAX(M.FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO M
    GROUP BY FOOD_TYPE
) R
    ON L.FOOD_TYPE = R.FOOD_TYPE
WHERE L.FAVORITES = R.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;