-- 코드를 입력하세요
SELECT
    T.USER_ID,
    T.NICKNAME,
    T.TOTAL_SALES
FROM (
    SELECT 
        U.USER_ID,
        U.NICKNAME,
        SUM(L.PRICE) AS TOTAL_SALES
    FROM (
        SELECT * FROM USED_GOODS_BOARD B
        WHERE B.STATUS = 'DONE'
    ) L
    LEFT JOIN USED_GOODS_USER U
        ON L.WRITER_ID = U.USER_ID
    GROUP BY L.WRITER_ID
) T
WHERE T.TOTAL_SALES >= 700000
ORDER BY T.TOTAL_SALES ASC;