# -- 코드를 작성해주세요
SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
LEFT JOIN ITEM_INFO I
    ON T.ITEM_ID = I.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
    SELECT P.ITEM_ID AS P_ITEM_ID
    FROM ITEM_INFO P
    WHERE P.RARITY = 'RARE'
        AND P.ITEM_ID IN (
            SELECT T2.PARENT_ITEM_ID 
            FROM ITEM_TREE T2
            GROUP BY T2.PARENT_ITEM_ID
    )
) 
ORDER BY T.ITEM_ID DESC;


