-- 코드를 입력하세요
SELECT *
FROM (
    SELECT 
        MONTH(H.START_DATE) AS MONTH,
        CAR_ID,
        COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE CAR_ID IN (
        SELECT CAR_ID AS T_CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID HAVING COUNT(*) >= 5
    ) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY MONTH(H.START_DATE), H.CAR_ID
) C
WHERE C.RECORDS > 0
ORDER BY C.MONTH ASC, C.CAR_ID DESC;
