-- 코드를 작성해주세요
SELECT
    YEAR(L.DIFFERENTIATION_DATE) AS YEAR,
    R.MAX_SIZE_OF_YEAR - L.SIZE_OF_COLONY AS YEAR_DEV,
    L.ID
FROM ECOLI_DATA L
LEFT JOIN (
    SELECT
        ID,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_YEAR,
        YEAR(DIFFERENTIATION_DATE) AS E_YEAR
    FROM ECOLI_DATA
    GROUP BY E_YEAR
) R 
    ON YEAR(L.DIFFERENTIATION_DATE) = R.E_YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;