-- 코드를 작성해주세요

SELECT ID, FISH_NAME, MAX_LENGTH AS LENGTH
FROM FISH_INFO I
LEFT JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
    ON M.FISH_TYPE = I.FISH_TYPE
    AND M.MAX_LENGTH = I.LENGTH
ORDER BY I.ID ASC;