-- 코드를 작성해주세요
SELECT 
    L.DEPT_ID,
    L.DEPT_NAME_EN,
    R.AVG_SAL
FROM HR_DEPARTMENT L
JOIN (
    SELECT 
        DEPT_ID,
        ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
) R 
    ON L.DEPT_ID = R.DEPT_ID
ORDER BY R.AVG_SAL DESC;
