-- 코드를 작성해주세요

SELECT 
    COUNT(*) AS FISH_COUNT,
    MAX(A.NOT_NULL_LENGTH) AS MAX_LENGTH,
    A.FISH_TYPE AS FISH_TYPE
FROM (
    SELECT *, IFNULL(N.LENGTH, 10) AS NOT_NULL_LENGTH
    FROM FISH_INFO N
) A
GROUP BY FISH_TYPE HAVING AVG(A.NOT_NULL_LENGTH) >= 33
ORDER BY A.FISH_TYPE ASC